name: Greating
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to great"
        required: true
        default: "Mona"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      # refering to the input parameters at workflow dispatch
      - run: |
          echo "Hello ${{ github.event.inputs.name }}"

      # say hello with JS action
      - name: "Checkout my action from this repository"
        uses: actions/checkout@v4
      - name: "Installing node dependencies"
        run: npm install
      - name: "Greeting with my-action"
        # assign id that is referenced in the next step
        id: hello
        uses: ./.github/actions/my-action
        with:
          who-to-greet: ${{ github.event.inputs.name }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
