name: Greating
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to great"
        required: true
        default: "Mona"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      # refering to the input parameters are workflow dispatch
      - run: |
          echo "Hello ${{ github.event.inputs.name }}"
